exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'

general {
    col.active_border = rgba(751A2Aff) rgba(FFCCD5ff) 45deg
    col.inactive_border = rgba(F4E5E8ff) rgba(E393A0ff) 45deg
}

group {
    col.border_active = rgba(751A2Aff) rgba(FFCCD5ff) 45deg
    col.border_inactive = rgba(F4E5E8cc) rgba(E393A0cc) 45deg
    col.border_locked_active = rgba(F5F6F6ff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(030303cc) rgba(0A0C0Bcc) 45deg
}
